### PR TITLE
Fixed bug with Proxy-Authorization header value

### PR DESCRIPTION
**Pull request by clicktravel-basharat**

### CODE REVIEW

**Comment by clicktravel-basharat** [comment]
Checked by @clicktravel-james

**Comment by clicktravel-james** [comment]
@clicktravel-basharat : I am happy. Good to gone :).

**Comment by clicktravel-basharat** [comment]
@ClickTravel/cheddarchapter  Test

**Comment by clicktravel-robin** [comment]
ok

**Pull request merged**
