### PR TITLE
DP-121 Allow locally modified properties file to have 'dev-' prefix

### PR DESCRIPTION
**Pull request by clicktravel-steffan**
Locally modified properties file can have 'dev-' prefix. The 'local-' prefix is still accepted, but is now deprecated.
This (breaking) change also fixes a Spring Framework WARN on startup concerning PropertySourcesPlaceholderConfigurer.

Signed-off-by: Steffan Westcott <steffan.westcott@clicktravel.com>

### CODE REVIEW

**Comment by clicktravel-basharat** [comment]
It will break because there is no "dev-"... properties file. Might be worth putting out a post before this version of Cheddar is used.

**Comment by clicktravel-basharat** [comment]
Good to go.

**Comment by clicktravel-steffan** [comment]
@clicktravel-basharat Actually, this will simply emit a WARN message if the 'dev-' properties file cannot be found. The following line (present in this pull request) makes this happen:
```java
configurer.setIgnoreResourceNotFound(true);
```

**Comment by clicktravel-basharat** [comment]
How is this a breaking change then?

**Comment by clicktravel-steffan** [comment]
@clicktravel-basharat The method signature for ```PropertiesConfigurationBuilder#configurer``` has changed. An ```Environment``` parameter has been changed to a simple ```boolean```, to indicate if this is a ```dev``` (or ```local```) environment. This change is part of the solution to avoid the Spring Framework WARN issues I mentioned earlier.

**Comment by clicktravel-basharat** [comment]
Still good to go.

**Pull request merged**
