### PR TITLE
DET-9 Log Java version and vendor info on app start

### PR DESCRIPTION
**Pull request by clicktravel-steffan**

### CODE REVIEW

**Comment by clicktravel-robin** [comment]
Well it looks like it will do what you say :), whats the purpose of this change?

**Comment by clicktravel-basharat** [comment]
Better to put as logging to be picked up by Logentries.

**Comment by clicktravel-steffan** [comment]
@clicktravel-robin The purpose is to help prove the version (identity) of the JRE execution environment. This is to ensure rollout of JREs is in place before deployment of apps that make use of new language features, for example.

**Comment by clicktravel-steffan** [comment]
I've changed the implementation to log the Java info rather than expose it via a REST resource. Ready for next review.

**Comment by clicktravel-basharat** [comment]
Looking better. Any further comments @clicktravel-robin ?

**Pull request merged**
